Encoding:
  Enabled: False
LineLength:
  Max: 600
Documentation:
  Enabled: False
Style/SpaceBeforeFirstArg:
  Enabled: false
AsciiComments:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
